-- Seed Vanta Wholesaling Lessons (8 Modules, 43 Units)
TRUNCATE TABLE public.lessons CASCADE;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-1', 'The Mindset of a Wholesaler', 'module-1', 50, '{"slides":[{"title":"Value Sourcing over Capital","text":"Welcome to Vanta. Real estate wholesaling is not about having millions of dollars in the bank or stellar credit scores. Instead, wholesaling is a business built on value creation: finding off-market opportunities that other investors cannot easily locate, and putting them under contract. By doing this, you are solving a major puzzle piece for real estate cash buyers who have capital but lack the time to seek out heavily discounted deals."},{"title":"Skill & Daily Persistence","text":"To succeed in wholesaling, you must adopt the mindset of an entrepreneur who treats this as a active career, not a get-rich-quick scheme. Your primary assets are consistency, persistence, and communication. Sourcing deals requires marketing to sellers daily, handling conversations calmly, and sorting through properties. In real estate, consistency beats talent every single time. One conversation a day can completely transform your business trajectory."},{"title":"Solving Problems First","text":"Successful wholesalers approach sellers not with the intention to simply close a transaction, but with the goal of solving a real problem. You are helping sellers who are in tough situations (such as foreclosure, inheritance tax issues, or owning a property needing repairs they cannot afford). When you shift your perspective from making a quick dollar to providing speed, convenience, and relief to a seller, you build a sustainable and ethical business."}],"quiz":{"question":"What is the most critical asset for a successful real estate wholesaler?","options":["A massive amount of personal investment capital","A licensed real estate brokerage firm association","Consistency, persistence, and a problem-solving mindset"],"answer":2}}', 1)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-2', 'What Is Real Estate Wholesaling', 'module-1', 50, '{"slides":[{"title":"The Wholesaling Mechanics","text":"At its core, real estate wholesaling is the practice of finding discounted off-market properties, locking them under a Purchase and Sale Agreement (PSA) with the seller, and then assigning that contract to an end cash buyer for an assignment fee. The wholesaler does not purchase the physical house, nor do they take title. Instead, they act as the connector, transferring the equitable interest of the contract to an investor."},{"title":"A Typical Wholesaling Deal","text":"Let''s break down a classic example. You find a motivated seller who agrees to sell their distressed property for $80,000. You sign a Purchase Agreement with them. Next, you market this opportunity to your list of cash buyers. An investor sees the potential and agrees to pay $90,000 for the property contract. You execute an Assignment of Contract, transferring your buyer rights to them. The investor closes, pays the seller $80,000, and you receive the remaining $10,000."},{"title":"Equitable Interest & Licensing","text":"It is vital to understand that you are not selling houses—which requires a real estate agent license. Instead, you are marketing and selling the contract that you own. Once you sign a Purchase Agreement as the buyer, you hold \"equitable interest\" in the property. This interest is a legal asset that you are fully authorized to sell or assign, provided the contract allows for assignment."}],"quiz":{"question":"In a standard wholesaling transaction, what does the wholesaler actually sell to the cash buyer?","options":["The physical brick-and-mortar property","The Purchase and Sale contract (equitable interest)","A real estate broker representation agreement"],"answer":1}}', 2)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-3', 'Why Wholesaling Works', 'module-1', 50, '{"slides":[{"title":"Sellers Seeking Speed & Simplicity","text":"Wholesaling exists because many property owners cannot sell their homes through traditional retail channels. Listing with an agent requires cleaning, hosting showings, staging, making repairs, and waiting months for bank mortgage approvals. If a seller owns a severely damaged home or is facing urgent life crises (such as inheritance taxes, divorce, or medical bills), they prioritize speed and simplicity over absolute top dollar."},{"title":"Solving Urgent Situations","text":"Your service provides quick cash solutions to distressed situations. A seller who is weeks away from a foreclosure auction doesn''t have time to wait for a traditional buyer. By offering an all-cash close in as little as 10 to 14 days, with no inspection contingencies or closing costs, you provide massive relief. The discount they give you is the price they willingly pay for convenience."},{"title":"Creating Win-Win Deals","text":"Wholesaling is a win-win-win mechanism. The seller is relieved of a burdensome property quickly. The cash buyer acquires a profitable investment deal that they did not have to market for. You, the wholesaler, receive compensation for finding the opportunity and bridging the gap. Remember: you are in the business of helping people first—the profits are a direct result of the value you deliver."}],"quiz":{"question":"Why do motivated sellers agree to sell their properties to wholesalers at a discount?","options":["Because they are unaware of the retail market value of their property","Because they value speed, convenience, and a quick cash close over a slow retail sale","Because they are legally required to work with real estate scouts"],"answer":1}}', 3)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-4', 'The Three Phases of Wholesaling', 'module-1', 50, '{"slides":[{"title":"Phase 1: Marketing","text":"The first phase is Lead Generation or Marketing. Without leads, your business has no pipeline. In this phase, you actively identify and contact property owners who might be motivated to sell. This involves pulling lists (such as code violations, tax defaults, or probates), driving for dollars, skip tracing numbers, and cold calling or texting to find hand-raisers."},{"title":"Phase 2: Acquisitions","text":"Once you find a lead who wants to sell, you enter Acquisitions. This phase covers building rapport with the seller, identifying the property condition, calculating its value (ARV and rehab costs), determining the Maximum Allowable Offer (MAO), negotiating terms, and securing a signed Purchase and Sale Agreement."},{"title":"Phase 3: Dispositions","text":"The final phase is Dispositions. Now that you have a deal locked up, you must match it with a cash buyer. This involves marketing the contract to your cash buyers list, vetting investors, executing an assignment contract, coordinate with a wholesaling-friendly title company, and managing the escrow process to ensure a successful closing."}],"quiz":{"question":"Negotiating deals and securing purchase contracts with property owners falls under which phase of wholesaling?","options":["Marketing","Acquisitions","Dispositions"],"answer":1}}', 4)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-5', 'Understanding Motivated Sellers', 'module-2', 50, '{"slides":[{"title":"Situations Over Property Aesthetics","text":"To find deep real estate discounts, you must seek out motivated sellers. Retail home buyers look for beautiful houses in perfect school districts. Wholesalers look for motivated sellers—people facing specific circumstances that make them need to sell a property quickly. The condition of the house is secondary; the seller''s situation is primary. Focus your marketing on situations, not structures."},{"title":"Sellers vs. Unmotivated Owners","text":"An unmotivated seller wants to list their home for a premium price and is willing to wait months for it. A motivated seller, however, has a pressing timeline. They might be relocating for a new job, dealing with a vacant property that is costing them taxes, or handling an inheritance they don''t want. Understanding their underlying motivation is the key to presenting an offer that solves their problem."},{"title":"Key Questions to Ask","text":"When speaking with potential leads, ask open-ended questions to determine their motivation level: \"Why are you looking to sell this property?\", \"How fast do you need to close?\", and \"What is stopping you from listing this property with a real estate agent?\". The answers to these questions will immediately tell you if you are dealing with a motivated seller or someone just testing the market."}],"quiz":{"question":"Which of the following is a primary characteristic of a motivated seller?","options":["They want to wait for the highest possible retail offer on the MLS","They have a pressing timeline and prioritize convenience and speed over top price","They have recently fully renovated their property"],"answer":1}}', 5)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-6', 'Lead Types Explained', 'module-2', 50, '{"slides":[{"title":"Free Government Lists","text":"Some of the best motivated seller leads can be obtained for free directly from city or county offices. These list types represent legal or physical distress: Code Violations (properties fined for structural damage or overgrown grass), Tax Delinquent lists (owners behind on property taxes), Probate (inheritors who want cash instead of real estate), and Water Shut-Off lists."},{"title":"Paid or Manual Lists","text":"You can also pull targeted lists from data providers or locate them manually. Absentee Owners are landlords who live out of state and may be tired of dealing with tenants. Vacant Properties are homes that are currently empty and sitting neglected. Pre-Foreclosures represent owners who have defaulted on their mortgage payments and need to sell before the bank takes the home."},{"title":"Marketing to Sourced Lists","text":"Once you have these lists, the goal is to skip trace the owners to find their phone numbers or send direct mail postcards. Because these lists contain owners experiencing real distress, they yield a much higher conversion rate compared to random cold calling. Focus your energy on high-motivation lists to maximize your marketing budget."}],"quiz":{"question":"Which of the following list types is typically obtained for free from municipal records?","options":["Out-of-state absentee owner list from a paid data provider","Code violations and municipal tax delinquency records","A nationwide pre-foreclosure list"],"answer":1}}', 6)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-7', 'Zillow FSBO Strategy', 'module-2', 50, '{"slides":[{"title":"Direct Sourcing on Zillow","text":"Zillow is a goldmine for free lead generation. By filtering for \"For Sale By Owner\" (FSBO) listings, you can connect directly with property owners without dealing with listing agents. These sellers are already trying to avoid paying real estate agent commissions, making them highly receptive to direct offers."},{"title":"Spotting Motivation on Market","text":"Not all FSBO sellers are motivated. To find the best leads, look for properties that have been on the market for more than 60 or 90 days, or have history of multiple price cuts. This indicates their original price expectation was too high, and they are becoming tired of trying to sell the property on their own."},{"title":"The Call Pitch","text":"When calling a Zillow FSBO owner, keep your script simple: \"Hi, I saw your property on Zillow. I''m a cash buyer looking for properties in the area. Are you open to a direct cash offer to close quickly?\". This direct approach filters out unmotivated sellers immediately and opens the door for negotiating terms."}],"quiz":{"question":"Which Zillow FSBO listing presents the highest probability of a successful wholesale negotiation?","options":["A newly listed property at a premium price point","A property listed for 90+ days with multiple price cuts","A listing that explicitly states \"no cash buyers or wholesalers\""],"answer":1}}', 7)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-8', 'Government Lists Strategy', 'module-2', 50, '{"slides":[{"title":"County Courthouse Sourcing","text":"Government lists are incredibly powerful because they capture distress early. Sourcing these lists requires contacting your local county clerk or city hall. Ask for the probate records, tax assessor''s list of properties with delinquent taxes, or code violation enforcement reports. These records are public information, though you may need to ask persistently."},{"title":"What Sourced Data Looks Like","text":"Delinquent tax lists show properties where owners are behind on their taxes, meaning they are at risk of losing their home to tax sale. Probate files show properties where the owner has passed away, and the heirs are going through court to distribute the estate. These heirs often prefer cash in hand over maintaining an old, inherited house."},{"title":"Skip Tracing and Outreach","text":"Once you receive a government list, you will have property addresses and owner names, but no phone numbers. Use online skip tracing platforms to cross-reference public records and obtain cell phone numbers. Once skip traced, you can immediately start cold calling, sending text messages, or mailing letters."}],"quiz":{"question":"Why are county probate lists considered highly motivated leads?","options":["Heirs often inherit distressed properties they do not want to manage and prefer a quick cash payout","The government automatically mandates that all probates must be wholesaled","Probate properties are always in pristine, market-ready condition"],"answer":0}}', 8)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-9', 'On-Market vs Off-Market Opportunities', 'module-2', 50, '{"slides":[{"title":"The Off-Market Advantage","text":"Off-market properties are deals not listed on the Multiple Listing Service (MLS). Because they are private transactions, there is virtually zero competition from retail buyers. This allows you to negotiate directly with the homeowner and secure deep discounts that would be impossible on the open market."},{"title":"The On-Market MLS Landscape","text":"On-market properties are listed by real estate agents on the MLS. Wholesaling these is more challenging because real estate agents represent the seller''s financial interests and will push for top dollar. In addition, agents usually require a licensed buyer, large earnest money deposits, and proof of funds."},{"title":"Targeting MLS Stale Listings","text":"If you want to wholesale on-market, look for properties that have been active on the MLS for over 100 days. These listings are considered \"stale,\" and the listing agent is often eager to get any reasonable offer closed. Always submit offers with assignable contract addendums to preserve your exit strategy."}],"quiz":{"question":"What is the main reason wholesalers prioritize off-market properties?","options":["They are listed on retail platforms like Realtor.com","They allow direct negotiation with the seller and have minimal competition","They require licensed brokers to handle the transaction"],"answer":1}}', 9)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-10', 'Driving for Dollars', 'module-2', 50, '{"slides":[{"title":"Physically Sourcing Distress","text":"Driving for Dollars (D4D) is the process of driving through target neighborhoods to physically identify distressed, vacant, or neglected properties. It is one of the most cost-effective lead generation strategies for beginners because it creates a highly customized list that cannot be purchased online."},{"title":"Spotting distressed homes","text":"When driving, look for properties with clear signs of neglect: overgrown yards, boarded-up windows, roofs with blue tarps, mail piling up in the mailbox, peeling paint, or code violation stickers on the front door. These visual cues strongly suggest that the owner has abandoned the property or cannot afford maintenance."},{"title":"Building Your D4D List","text":"Use mobile apps or note down the addresses of the distressed houses you find. Once you return, look up the owner''s name on your local county tax assessor website. Skip trace their contact details to call them or send them a handwritten mailer stating that you want to buy their property in its current condition."}],"quiz":{"question":"What type of property are you looking for when driving for dollars?","options":["Newly built homes in upscale master-planned communities","Properties showing physical signs of neglect, abandonment, or distress","Apartment complexes with full occupancy"],"answer":1}}', 10)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-11', 'Seller Psychology', 'module-3', 50, '{"slides":[{"title":"People Sell Situations","text":"To negotiate effectively, you must master seller psychology. Homeowners do not sell their houses to wholesalers because of the physical structure; they sell because of their situation. Whether they are dealing with a stressful inheritance, a pending foreclosure, a bad tenant, or a job relocation, they are selling a problem. Your goal is to understand that problem."},{"title":"Empathy Over Transactional Pitching","text":"Do not approach conversations with a hard sales pitch. Instead, listen actively and show genuine empathy. A seller who feels heard and understood will trust you. In wholesaling, trust is the currency that secures deals. If a seller does not trust you, they will never agree to sign a contract, regardless of your offer price."},{"title":"Speed, Convenience, and Certainty","text":"A motivated seller values three things: speed (closing fast), convenience (selling the property exactly as-is without cleanups or repairs), and certainty (knowing that the transaction will actually close). Position your wholesale offer as a stress-free solution that guarantees these three pillars."}],"quiz":{"question":"What is the most effective approach when discussing a deal with a seller?","options":["Pritching a highly aggressive, transactional sales pitch to pressure them","Listening actively with empathy to understand and solve their situation","Focusing purely on pointing out the physical defects of their home"],"answer":1}}', 11)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-12', 'The Four Pillars Framework', 'module-3', 50, '{"slides":[{"title":"Motivation & Timeline","text":"The Four Pillars of wholesaling qualification are: Motivation, Timeline, Condition, and Asking Price. Sourcing these four components on your initial call is essential. Motivation is the \"why\" behind the sale. Timeline determines how quickly they need the cash (e.g., \"in 30 days\" vs. \"next year\")."},{"title":"Condition & Asking Price","text":"Condition covers the physical state of the property, including age of the roof, HVAC system, and plumbing. This helps you estimate rehab costs. Asking Price is the starting point of negotiations. Knowing the seller''s initial price expectation allows you to compare it to the MAO."},{"title":"Qualifying Your Leads","text":"If a lead refuses to share their asking price, timeline, or condition, they are not yet qualified. Do not waste time analyzing numbers for unmotivated leads. Ensure you gather information on all four pillars before proceeding to underwriting or making an offer."}],"quiz":{"question":"What are the Four Pillars of wholesaling lead qualification?","options":["Marketing, Acquisitions, Dispositions, and Closing","Motivation, Timeline, Condition, and Asking Price","ARV, Rehab Cost, Wholesale Fee, and MAO"],"answer":1}}', 12)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-13', 'Building Rapport and Trust', 'module-3', 50, '{"slides":[{"title":"The Mirroring Technique","text":"Rapport is built by matching the seller''s conversational tone, pace, and vocabulary. If a seller speaks slowly and quietly, adjust your voice to match. Mirroring their communication style makes them feel comfortable and builds subconscious trust."},{"title":"Finding Common Ground","text":"During the conversation, listen for clues about their life, family, or hobbies. If they mention a pet, their city, or a sports team, validate it and share a brief personal connection. People do business with people they like and trust."},{"title":"Honesty and Setting Expectations","text":"Be transparent about your business model. Tell them directly: \"I am an investor looking to buy properties at a discount to renovate them or partner with other local builders. In exchange for the discount, I close fast with cash and pay all closing fees.\" Honesty builds long-term trust."}],"quiz":{"question":"How should you build rapport with a motivated homeowner?","options":["By hiding your intention to resell the contract","By matching their conversational tone and finding genuine common ground","By offering them retail list price initially and reducing it later"],"answer":1}}', 13)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-14', 'Seller Scripts and Objection Handling', 'module-3', 50, '{"slides":[{"title":"The Soft Script Flow","text":"When calling a seller, avoid sounding like a telemarketer. Use a casual script: \"Hi, I know this is out of the blue, but I was calling about the house on Elm Street. I was wondering if you''d be open to a cash offer on it?\". This soft approach lowers their defenses."},{"title":"Handling \"Your Offer is Too Low\"","text":"When a seller objects to your offer, do not get defensive. Validate their concern: \"I completely understand that price is important to you. Based on the repairs needed, this is the highest cash offer we can make. If we close fast in 10 days and pay all closing costs, what is the absolute best you could do?\"."},{"title":"Handling \"Are You a Realtor?\"","text":"If a seller asks if you are an agent, clarify immediately: \"No, I''m not an agent. I don''t list houses or charge commission fees. I buy contracts directly as a principal investor, which saves you 6% in commissions.\""}],"quiz":{"question":"How should you respond if a seller objects that your cash offer is too low?","options":["Argue with them about the local comps and demand they accept it","Acknowledge their concern, restate the benefits of a cash close, and ask for their absolute best number","Hang up immediately and move to the next lead"],"answer":1}}', 14)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-15', 'Negotiation Fundamentals', 'module-3', 50, '{"slides":[{"title":"The Power of Silence","text":"One of the most powerful negotiation tools is silence. After you present your offer, stop talking. The first person to speak usually loses leverage. Let the seller process the offer and respond first, even if the silence feels uncomfortable."},{"title":"Anchoring the Offer Price","text":"Start your negotiations below your Maximum Allowable Offer (MAO). This gives you room to negotiate upward if the seller counters. Never start negotiations at your absolute maximum limit, or you will leave yourself no room to find a middle ground."},{"title":"The Conditional Close","text":"Use conditional phrasing to secure agreement: \"If I could handle all the cleanout costs and close on the exact date of your choice, would you be ready to move forward today?\". This ties their requests to a commitment to sign the contract."}],"quiz":{"question":"What is a fundamental rule when presenting an offer price to a seller?","options":["Start negotiations at your maximum allowable offer to show you are serious","Start negotiations below your MAO to leave room for counters and compromises","Only present offers in writing without verbal discussions first"],"answer":1}}', 15)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-16', 'Understanding ARV', 'module-4', 50, '{"slides":[{"title":"What is After Repair Value?","text":"After Repair Value (ARV) is the estimated retail market value of a property after it has been fully renovated to modern, top-tier standards. It represents what a retail homebuyer would pay for the property on the open market after renovations are complete."},{"title":"ARV vs. Current Condition Value","text":"Do not confuse ARV with the current value of the distressed property. A house might be worth $100,000 in its current damaged state, but if fully renovated, similar homes in the neighborhood sell for $200,000. The ARV is $200,000. This is the baseline number from which you subtract repairs and fees."},{"title":"The Foundation of Deal Math","text":"Every wholesaling deal calculation starts with the ARV. If your ARV is incorrect, your entire offer calculation (MAO) will be wrong. This can lead to offering too much money to the seller, making it impossible to find a cash buyer."}],"quiz":{"question":"What does ARV represent in real estate valuation?","options":["The current value of the property in its distressed condition","The estimated retail value of the property after complete modern renovation","The annual rental income of the property"],"answer":1}}', 16)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-17', 'Running Comparable Sales', 'module-4', 50, '{"slides":[{"title":"Finding Comparable Sales (Comps)","text":"To calculate ARV, you must run \"comps\"—recently sold properties that are highly similar to your subject property. Comps must meet three strict criteria: sold within the last 6 months, located within a 0.5-mile radius, and similar in size, age, and layout."},{"title":"Selecting the Best Comps","text":"Look for properties with similar bedroom and bathroom counts, and similar square footage (within 15-20% variance). Ensure you are comparing apples to apples: do not compare a single-story ranch home to a two-story colonial, or a home next to a highway to one in a quiet cul-de-sac."},{"title":"Calculating the Average ARV","text":"Find 3 or 4 of the highest-selling, fully-renovated comps that match your property. Calculate their average sale price per square foot or average total sale price. This average represents your subject property''s estimated ARV."}],"quiz":{"question":"Which of the following is a correct criteria for selecting a comparable property (comp)?","options":["A property sold 2 years ago in a neighboring city","A property sold within the last 6 months within a 0.5-mile radius with similar square footage","Any active listing currently on the MLS regardless of status"],"answer":1}}', 17)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-18', 'Repair Estimation', 'module-4', 50, '{"slides":[{"title":"Why Rehab Estimates Matter","text":"Accurately estimating repair costs is vital. If you underestimate the cost of repairs, your cash buyer''s profit margin will shrink, and they will walk away from your deal. As a beginner, you don''t need a detailed contractor bid, but you must understand rough estimation ranges."},{"title":"Square Foot Estimation Method","text":"Use a rough square footage cost baseline: Light Cosmetic rehab (carpet, paint, minor fixtures) is $15–$25 per sq ft. Medium rehab (cosmetic plus kitchen/bath upgrades, minor HVAC) is $30–$50 per sq ft. Heavy rehab (foundation, roof, gut remodel) is $60+ per sq ft."},{"title":"Example Calculation","text":"If you have a 1,500 square foot home that needs a medium remodel (kitchen, bathrooms, flooring, interior paint), you calculate: 1,500 sq ft * $40/sq ft = $60,000 estimated repair cost. Always add a 10% buffer to your estimate to account for unforeseen issues."}],"quiz":{"question":"If a 1,200 sq ft house requires a light cosmetic remodel estimated at $20 per sq ft, what is the total estimated repair cost?","options":["$12,000","$24,000","$36,000"],"answer":1}}', 18)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-19', 'Understanding MAO', 'module-4', 50, '{"slides":[{"title":"The Maximum Allowable Offer Formula","text":"The Maximum Allowable Offer (MAO) is the absolute highest price you can offer the seller for the property contract to ensure your cash buyer makes a profit and you secure your wholesale fee. The industry-standard formula is: MAO = (ARV * 70%) - Rehab Cost - Wholesale Fee."},{"title":"Why the 70% Rule?","text":"The 70% rule assumes the cash buyer requires a 30% margin. This margin covers the investor''s target profit (15-20%), interest fees on hard money loans, holding costs (taxes, insurance), and buying/selling closing costs. In expensive markets, some buyers may buy at 75-80%, but 70% is the safest baseline."},{"title":"A Step-by-Step Example","text":"Let''s calculate: ARV is $200,000. Estimated rehab is $40,000. Your target wholesale fee is $10,000. MAO = ($200,000 * 0.70) - $40,000 - $10,000. MAO = $140,000 - $40,000 - $10,000 = $90,000. You cannot offer the seller more than $90,000."}],"quiz":{"question":"Using the 70% rule, if ARV is $300,000, repairs are $50,000, and your wholesale fee is $15,000, what is the MAO?","options":["$145,000","$160,000","$210,000"],"answer":0}}', 19)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-20', 'Evaluating Deal Profitability', 'module-4', 50, '{"slides":[{"title":"Analyzing Cash Buyer Yields","text":"To market a contract successfully, you must ensure the deal is highly profitable for your cash buyer. Investors look at returns: Return on Investment (ROI) or net margins. If a buyer spends $150k purchasing and renovating a house with an ARV of $200k, their margin is 25%, making it a highly attractive deal."},{"title":"Wholesale Fee vs. Buyer Profit","text":"Be reasonable with your wholesale fee. If you lock a property under contract for $100k, and the MAO is $110k, trying to charge a $30k fee will kill the deal. Keep your fee balanced so that the cash buyer still has a strong incentive to take the contract off your hands."},{"title":"The Danger of Tight Margins","text":"If a deal has tight margins (e.g., buyer profit is only 5-10% of ARV), any delay or unexpected repair cost will make the deal unprofitable. Cash buyers will avoid these deals. Always leave enough cushion in your calculations to ensure profitability."}],"quiz":{"question":"What happens if a wholesaler tries to charge an excessive fee that pushes the buyer''s purchase price above MAO?","options":["The cash buyer will gladly buy the contract anyway","The deal will fail to sell because the investor''s profit margin is eliminated","The seller is forced to reduce their price further by law"],"answer":1}}', 20)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-21', 'Property Photo Collection and Documentation', 'module-4', 50, '{"slides":[{"title":"The Power of Visual Proof","text":"Cash buyers will not purchase a contract without seeing visual proof of the property''s condition. You must take clear, high-quality photos and videos of the property. Photos serve as documentation for your rehab estimates and prove the condition to your buyers list."},{"title":"How to Take Good Photos","text":"Walk through every room and capture wide-angle shots. Be sure to photograph the major systems: the electrical panel, the HVAC unit, the water heater, the roof, and any visible damage (cracks in walls, water stains, mold). Take photos of the front, back, and sides of the house."},{"title":"Organizing the Deal Package","text":"Compile your photos into a shared Google Drive or Dropbox folder. Group them logically (e.g., Exterior, Interior, Mechanicals). Include a brief written summary detailing the property specs, age of mechanical systems, and estimated repairs. A professional package sells contracts fast."}],"quiz":{"question":"Which photos are most critical to include in your deal marketing package for cash buyers?","options":["Only close-up photos of clean, renovated parts of the house","Wide shots of every room, along with photos of the roof, HVAC, electrical panel, and visible damage","A single photo of the front yard"],"answer":1}}', 21)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-22', 'Purchase Agreements', 'module-5', 50, '{"slides":[{"title":"The Purchase and Sale Agreement (PSA)","text":"The Purchase and Sale Agreement (PSA) is the legally binding contract between you (the buyer) and the property owner (the seller). This document outlines the purchase price, closing date, escrow details, and terms of the transaction."},{"title":"The Assignability Clause","text":"For a contract to be wholesaled, it must be assignable. Ensure your PSA contains an assignability clause, or states that the buyer is: \"Your Name and/or Assigns\". This language gives you the legal right to assign the contract to another investor."},{"title":"Standard Contingencies","text":"Always include a \"buyer inspection window\" (contingency clause) of 10 to 15 days. This window gives you time to access the property with your cash buyers and partners, run inspections, and cancel the contract if you discover major hidden structural defects."}],"quiz":{"question":"What contract language grants you the legal right to wholesale a Purchase Agreement?","options":["A clause stating the contract cannot be transferred under any condition","Naming the buyer as \"Your Name and/or Assigns\" or including an assignability clause","Listing a real estate broker commission fee"],"answer":1}}', 22)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-23', 'Earnest Money Deposits', 'module-5', 50, '{"slides":[{"title":"What is Earnest Money?","text":"Earnest Money Deposit (EMD) is a good faith deposit submitted by the buyer to prove to the seller that they intend to close the deal. EMD is not paid directly to the seller; it is held in a neutral escrow account by a title company."},{"title":"EMD Guidelines for Wholesalers","text":"As a wholesaler, keep your EMD as low as possible (typically $100 to $500). This limits your financial risk while keeping the contract legally binding. Once the contract is signed, you must deposit the EMD with the title company within 2 to 3 business days."},{"title":"Protecting Your Deposit","text":"Your inspection contingency protects your EMD. If you cancel the contract within your inspection window because the deal doesn''t make sense, the title company must return your EMD in full. Ensure your contract explicitly states this protection."}],"quiz":{"question":"Who holds the Earnest Money Deposit during a wholesaling transaction?","options":["The seller holds it in their personal bank account","A neutral third-party title company or escrow agent holds it in an escrow account","The wholesaler keeps it in their wallet"],"answer":1}}', 23)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-24', 'Assignment Contracts', 'module-5', 50, '{"slides":[{"title":"The Assignment Agreement","text":"Once you find a cash buyer, you sign an Assignment of Contract agreement. This document transfers all your rights and obligations under the original Purchase Agreement to the new buyer in exchange for an assignment fee."},{"title":"Structuring the Assignment Fee","text":"The Assignment contract specifies your wholesale fee and when it is paid. It is paid at the final closing table by the title company out of the buyer''s funds. Never accept fees directly from the buyer prior to closing, unless it is a non-refundable buyer deposit."},{"title":"Non-Refundable Buyer EMD","text":"Ensure the cash buyer deposits a non-refundable earnest money deposit (usually $2,500 to $5,000) with the title company immediately upon signing the assignment. This ensures that if the buyer defaults, you keep their EMD to cover your risk."}],"quiz":{"question":"When is the wholesaler''s assignment fee officially paid?","options":["Immediately when the cash buyer signs the assignment agreement","At the final closing of escrow out of the cash buyer''s funds","Thirty days after the buyer finishes renovating the property"],"answer":1}}', 24)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-25', 'Double Closings', 'module-5', 50, '{"slides":[{"title":"What is a Double Closing?","text":"A Double Closing (also known as an A-B, B-C transaction) involves purchasing the property from the seller (A to B) and then immediately selling it to your cash buyer (B to C) on the same day. This requires two separate closing transactions and closing costs."},{"title":"When to Use Double Closing","text":"Double closings are used to keep your wholesale fee private. In a standard assignment, the seller and buyer see your assignment fee on the closing statement. If your fee is very large (e.g., $30,000+), using a double closing prevents potential deal friction."},{"title":"Funding the Double Close","text":"Because you are executing two transactions, you must fund the first purchase (A-B) before selling to C. You can use \"transactional funding\"—a short-term 24-hour loan designed specifically for wholesalers to facilitate double closings."}],"quiz":{"question":"What is the primary advantage of executing a Double Closing?","options":["It eliminates all transaction fees and closing costs","It keeps the wholesaler''s assignment fee completely private from both the seller and the buyer","It allows you to sell the property without using a title company"],"answer":1}}', 25)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-26', 'Title Companies and Escrow', 'module-5', 50, '{"slides":[{"title":"Wholesaling-Friendly Title Companies","text":"Not all title companies understand or accept wholesaling assignments or double closings. It is critical to build relationships with \"investor-friendly\" title companies or real estate attorneys who specialize in escrow management for wholesale transactions."},{"title":"The Title Search Process","text":"Once you submit your contracts, the title company conducts a title search. This search ensures the seller legally owns the property and identifies any outstanding liens, unpaid taxes, or mortgages that must be paid off at closing to deliver a \"clear title\"."},{"title":"Managing the Escrow Account","text":"The title company acts as the neutral escrow agent. They receive the contracts, hold the buyer''s funds, pay off the seller''s mortgages, distribute the seller''s proceeds, and wire your assignment fee directly to your bank account upon closing."}],"quiz":{"question":"Why is it important to use an investor-friendly title company?","options":["They will skip the title search process to close faster","They understand the legal mechanics of contract assignments, double closings, and transactional funding escrow","They charge the seller a higher commission fee"],"answer":1}}', 26)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-27', 'Closing Process Walkthrough', 'module-5', 50, '{"slides":[{"title":"Step 1: Contract Submission","text":"The closing process begins the moment you submit both the signed Purchase Agreement and the Assignment Contract to your title agent. The title company will open escrow and begin their title search and administrative paperwork."},{"title":"Step 2: Clearing Title & Buyer Wiring","text":"The title company coordinates with the seller to resolve any title issues. Once the title search is complete and clear, the closing coordinator schedules the closing date. The cash buyer wires the full purchase amount into the escrow account."},{"title":"Step 3: Signing & Funding Disbursement","text":"On closing day, the seller signs the deed transferring the property. The buyer signs their closing disclosures. Once all signatures are verified, the title company distributes the funds: pays off the seller, and wires your assignment fee."}],"quiz":{"question":"What must occur before a title company can schedule the closing and disburse your assignment fee?","options":["The buyer must complete their property renovations","The title search must return clear, and the buyer must wire the full purchase funds into escrow","The seller must list the property on the MLS"],"answer":1}}', 27)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-28', 'Building a Cash Buyers List', 'module-6', 50, '{"slides":[{"title":"Your Buyers List is Your Income","text":"A wholesaler without cash buyers cannot close deals. Your cash buyers list is the foundation of your business. These are real estate investors (fix-and-flippers, landlords) who have the capital ready to purchase your assignable contracts."},{"title":"Where to Find Buyers","text":"Locate buyers through local Real Estate Investor Association (REIA) meetups, Facebook real estate investor groups, Craigslist advertisements, or by pulling public county records of properties recently purchased with cash in your target zip codes."},{"title":"Gathering Buyer Criteria","text":"When you find a potential buyer, ask for their buying criteria: \"What zip codes do you buy in?\", \"What is your target purchase price?\", \"What type of rehab do you prefer?\", and \"How do you fund your deals?\". Keep this details organized in a spreadsheet."}],"quiz":{"question":"Which of the following is a primary channel for locating cash buyers?","options":["Cold calling retail home buyers looking for their primary residence","Attending local REIA meetups and searching public records for recent cash sales","Posting signs in front of high-priced retail listings"],"answer":1}}', 28)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-29', 'Verifying Buyers', 'module-6', 50, '{"slides":[{"title":"Vetting Your Cash Buyers","text":"Many people claim to be cash buyers but lack the funds to close. As a wholesaler, you must vet your buyers before assigning contracts. Working with unverified buyers leads to deal fallout, which damages your relationship with the seller."},{"title":"Proof of Funds (POF)","text":"Always request a Proof of Funds (POF) letter. This should be a recent bank statement or a letter from a hard money lender proving they have the liquidity to cover the purchase and rehab costs. Ensure the name on the POF matches the buyer''s entity."},{"title":"Checking Closing History","text":"Ask the buyer: \"How many deals have you closed in the last 12 months?\" and \"Which title company do you use?\". A legitimate investor will easily provide references and point to their active projects."}],"quiz":{"question":"What document should you request to verify that a buyer is financially capable of closing a deal?","options":["A copy of their real estate license","A recent Proof of Funds (POF) letter or bank statement showing sufficient liquidity","A written promise letter signed by their partner"],"answer":1}}', 29)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-30', 'Buyer Relationship Management', 'module-6', 50, '{"slides":[{"title":"Managing Your Buyers List","text":"Building a buyers list is only the first step. To maintain a successful business, you must manage your buyer relationships professionally. Treat your buyers as valued business partners. Provide them with accurate calculations and transparent data."},{"title":"Segmenting Your Buyers","text":"Segment your buyers based on their buying criteria. Create lists for \"Fix & Flip Buyers,\" \"Buy & Hold Landlords,\" and \"Commercial Investors.\" This allows you to send targeted deals only to the buyers most likely to purchase them."},{"title":"Communication and Trust","text":"Be honest about property defects. If a house needs a new roof, state it clearly. Over-delivering and maintaining transparency builds massive trust, turning one-time buyers into repeat customers who close deals quickly."}],"quiz":{"question":"How can you build long-term trust with your cash buyers list?","options":["By underestimating repair costs to make deals look better","By being fully transparent about property condition and providing accurate calculations","By sending every single deal to all buyers regardless of their criteria"],"answer":1}}', 30)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-31', 'JV Partnerships', 'module-6', 50, '{"slides":[{"title":"What is a Joint Venture (JV)?","text":"A Joint Venture (JV) occurs when two wholesalers partner to close a deal. Typically, one wholesaler has the property under contract (the acquisitions partner), and the other wholesaler has access to the cash buyer (the dispositions partner)."},{"title":"The JV Agreement","text":"Always execute a written Joint Venture Agreement before sharing details or marketing a partner''s deal. This agreement outlines how the assignment fee will be split (typically 50/50) and protects both parties from being bypassed."},{"title":"Accelerating Your Deal Flow","text":"JV partnerships are a great way for beginners to close their first few deals. If you have a deal but no buyers list, partner with an established wholesaler. If you have a buyers list but no deals, partner with active scouts."}],"quiz":{"question":"How do joint venture (JV) partnerships benefit wholesalers?","options":["They allow wholesalers to pool their resources to buy properties for themselves","They combine one partner''s deal acquisition with another partner''s cash buyers list to close deals faster","They eliminate the need to use contracts"],"answer":1}}', 31)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-32', 'Disposition Process', 'module-6', 50, '{"slides":[{"title":"Marketing the Deal","text":"The disposition process begins once you have a signed Purchase Agreement. Create a compelling marketing package detailing property specs, photos, comps, ARV, rehab estimate, purchase price, and closing date."},{"title":"Sending the Email Blast","text":"Email the package to your segmented buyers list. Use a strong subject line: \"[DEAL] Distressed 3 Bed/2 Bath in [City] - Deep Discount.\" Set a deadline for offers to create urgency among buyers."},{"title":"Selecting the Best Offer","text":"Evaluate offers based on price and terms. A buyer offering $95k cash who can close in 7 days is often better than a buyer offering $100k who requires hard money financing and a 21-day close. Select the highest-certainty offer."}],"quiz":{"question":"What is the primary goal of the dispositions process?","options":["To find motivated sellers and negotiate prices","To market your assignable contract, locate a vetted cash buyer, and execute the assignment","To coordinate property renovations with general contractors"],"answer":1}}', 32)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-33', 'Introduction to Creative Finance', 'module-7', 50, '{"slides":[{"title":"What is Creative Finance?","text":"Creative Finance refers to alternative methods of purchasing real estate without relying solely on traditional bank mortgages or large cash reserves. It allows wholesalers to construct deals when a seller''s loan balance is too high for a cash offer."},{"title":"Why Creative Finance Matters","text":"Traditional cash offers require a property to be purchased at 30-40% below market value. If a seller wants to sell but owes $180,000 on a home worth $200,000, a cash offer of $130,000 will not work. Creative finance provides a path to close these transactions."},{"title":"The Core Strategies","text":"The primary creative finance strategies are: Subject-To (Sub2), Seller Financing, Lease Options, and Wrap Mortgages. Mastering these strategies allows you to monetize \"dead leads\" that do not fit standard cash MAO calculations."}],"quiz":{"question":"When is creative finance most useful for a wholesaler?","options":["When the property has a massive amount of equity and the seller wants a quick cash close","When a cash offer cannot work because the seller owes close to market value or wants retail price","When the buyer wants to use a traditional FHA bank mortgage"],"answer":1}}', 33)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-34', 'Subject-To Deals', 'module-7', 50, '{"slides":[{"title":"Understanding Subject-To (Sub2)","text":"Subject-To is a creative strategy where you purchase a property \"subject to\" the existing mortgage remaining in place. The seller deeds the property title to the buyer, but the mortgage loan remains in the seller''s name."},{"title":"How Sub2 Transactions Work","text":"The buyer takes ownership of the property and takes over the monthly mortgage payments. This is highly attractive to investors because they acquire a property with low-interest owner-occupied financing already in place, bypassing bank credit checks."},{"title":"The Due-on-Sale Clause","text":"All standard mortgages contain a \"due-on-sale\" clause, which gives the bank the right to demand full repayment if the property title transfers. While banks rarely enforce this if payments are made on time, wholesalers must disclose this risk."}],"quiz":{"question":"What happens to the existing mortgage in a Subject-To transaction?","options":["It is completely paid off and cancelled at closing by the buyer","It remains in place in the seller''s name, while the buyer takes title and assumes the monthly payments","The bank automatically transfers the loan name to the wholesaler"],"answer":1}}', 34)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-35', 'Seller Financing', 'module-7', 50, '{"slides":[{"title":"What is Seller Financing?","text":"Seller Financing (also known as owner financing) occurs when the seller acts as the bank. Instead of receiving a lump sum of cash at closing, the seller agrees to accept payments over time from the buyer at a negotiated interest rate."},{"title":"Structuring the Terms","text":"In seller financing, you negotiate the purchase price, down payment, interest rate, monthly payment amount, and balloon payment date. This is ideal for properties owned \"free and clear\" (no existing mortgages)."},{"title":"Why Sellers Agree to Owner Finance","text":"Sellers agree to owner financing to generate passive cash flow, secure monthly interest income, defer capital gains taxes, and sell a property that might not qualify for traditional bank financing due to condition issues."}],"quiz":{"question":"Who acts as the lender in a Seller Financing agreement?","options":["A traditional commercial mortgage bank","The property owner (seller) who agrees to accept payments over time","A hard money investment firm"],"answer":1}}', 35)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-36', 'Lease Options', 'module-7', 50, '{"slides":[{"title":"Understanding Lease Options","text":"A Lease Option (often called Rent-to-Own) combines a standard lease agreement with an option contract. The tenant-buyer leases the property for a set period and holds the option to purchase the property at a predetermined price before the lease expires."},{"title":"The Option Fee","text":"The tenant-buyer pays a non-refundable \"option fee\" upfront. This fee secures their exclusive option rights. If they choose not to purchase the property, the seller keeps the option fee and the lease simply terminates."},{"title":"Wholesaling Lease Options","text":"Wholesalers can contract a lease option with a seller, and then assign the lease option contract to a tenant-buyer for a lease option assignment fee (typically $3,000 to $10,000). This is a low-risk creative finance strategy."}],"quiz":{"question":"What is a Lease Option contract?","options":["A standard lease agreement that cannot be cancelled","A combination of a lease agreement and an option to purchase the property at a set price within a set timeline","A mortgage loan contract issued by the seller"],"answer":1}}', 36)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-37', 'Wrap Mortgages', 'module-7', 50, '{"slides":[{"title":"What is a Wrap Mortgage?","text":"A Wrap Mortgage (or \"wrap-around\") is a creative finance structure where a new mortgage \"wraps\" around an existing mortgage. The new mortgage includes the balance of the original loan plus additional equity or seller profit."},{"title":"How the Wrap Works","text":"The buyer makes a single monthly payment to the seller (or a third-party servicing company) at a set interest rate. The seller then uses a portion of those funds to pay their original mortgage lender, keeping the remaining interest spread."},{"title":"Legality and Servicing","text":"Wrap transactions are legal but must be structured carefully using professional licensed title agents and third-party note servicing companies to ensure the underlying mortgage payments are always made on time."}],"quiz":{"question":"How is a Wrap Mortgage structured?","options":["It is a new loan that wraps around and incorporates the existing mortgage balance and payments","It is a loan that paid off the original mortgage completely at closing","It is an unsecured personal line of credit"],"answer":0}}', 37)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-38', 'Marketing Creative Finance Deals', 'module-7', 50, '{"slides":[{"title":"Targeting Creative Finance Leads","text":"To market creative finance deals, look for sellers who have low equity, are behind on mortgage payments (pre-foreclosures), or have listed their properties for a long time without receiving cash offers."},{"title":"Pitching the Terms","text":"Present creative finance as a way for the seller to walk away with their asking price. Explain: \"I can pay your full asking price, but I need to pay it over time or take over your mortgage payments.\" This shifts the focus from price to terms."},{"title":"Marketing to Buyers","text":"Market creative finance contracts to investors looking for cash-flowing rental properties or lease-option buyers. Emphasize the low down payment, low interest rate, and lack of bank qualifying requirements."}],"quiz":{"question":"How should you pitch a creative finance offer to a seller?","options":["By demanding they reduce their price to fit a cash offer standard","By offering to meet their target purchase price in exchange for favorable payment terms or taking over their mortgage","By applying for a commercial bank mortgage in the seller''s name"],"answer":1}}', 38)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-39', 'Legal and Ethical Guidelines', 'module-8', 50, '{"slides":[{"title":"Understanding Local Laws","text":"Real estate laws vary by state and county. Some states have strict regulations regarding contract assignments and require specific disclosures or licensing. Always research your local real estate laws before wholesaling."},{"title":"Full Disclosure Policy","text":"Be transparent with all parties. Disclose to the seller that you are an investor purchasing the contract with intent to assign it for a profit. Disclose to the buyer your exact purchase terms and assignment fee."},{"title":"Avoiding Fraud and Misrepresentation","text":"Never market a property you do not have under contract. Never misrepresent the condition, repair estimates, or comps. Honesty and compliance with local laws protect your business and reputation."}],"quiz":{"question":"What is the most ethical practice when wholesaling contracts?","options":["Marketing a property you do not legally control under a signed contract","Disclosing your role as an investor purchasing with intent to assign the contract for a profit","Hiding the assignment fee from the cash buyer"],"answer":1}}', 39)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-40', 'Avoiding Beginner Mistakes', 'module-8', 50, '{"slides":[{"title":"Analysis Paralysis","text":"Many beginners get stuck in \"analysis paralysis\"—spending weeks studying lists and formulas without ever calling a seller. Sourcing deals requires taking action. Make calls, submit offers, and learn from feedback."},{"title":"Underestimating Rehab Costs","text":"A common mistake is underestimating repair costs. This makes your deals look better on paper but leads to buyers rejecting your contracts. Be conservative and add a repair buffer to protect your buyer''s margins."},{"title":"Failing to Qualify Leads","text":"Do not waste time negotiating with unmotivated owners. Use the Four Pillars framework to qualify leads quickly. Focus your energy only on owners who show real motivation and a clear timeline."}],"quiz":{"question":"How can you avoid the common mistake of analysis paralysis?","options":["By analyzing more property data for another six months without marketing","By taking daily action: marketing to lists, skip tracing, and calling leads","By listing uncontracted properties on Craigslist"],"answer":1}}', 40)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-41', 'Scaling Operations', 'module-8', 50, '{"slides":[{"title":"Reinvesting Your Profits","text":"Once you close your first few deals and earn assignment fees, reinvest a portion of your profits back into your business. Upgrade your marketing channels, buy larger lists, and invest in better systems."},{"title":"Hiring Virtual Assistants (VAs)","text":"Scale your time by hiring Virtual Assistants (VAs). VAs can handle repetitive tasks such as list pulling, skip tracing, cold calling, and managing database entry, leaving you free to focus on acquisitions."},{"title":"Expanding Your Target Markets","text":"Once you master your local market, expand into virtual wholesaling. Target neighboring counties or states with high investor activity and strong cash buyer demand, running negotiations entirely online."}],"quiz":{"question":"What is a key step to successfully scale your wholesaling operations?","options":["Spending all assignment profits on personal luxury items immediately","Reinvesting profits in automated marketing channels and hiring help for repetitive tasks","Stopping all marketing to focus on closing a single active lead"],"answer":1}}', 41)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-42', 'Systems and Automation', 'module-8', 50, '{"slides":[{"title":"Implementing a CRM","text":"A Customer Relationship Management (CRM) system is vital to track your leads. A good CRM records contact histories, schedules follow-ups, and pipelines your active negotiations from lead to closed."},{"title":"Automating Lead Follow-Up","text":"Most deals are closed in the follow-up. Set up automated email and SMS drip campaigns to keep in touch with leads who are not yet ready to sell. Regular touchpoints ensure they call you when motivation strikes."},{"title":"Key Software Tools","text":"Master key tools such as PropStream for pulling lists, batch skip tracing, deal calculators, and electronic signing software to execute contracts instantly. Systems create a predictable sales machine."}],"quiz":{"question":"Why is automated lead follow-up essential in wholesaling?","options":["It automatically buys the property without contracts","Most motivated sellers close in the follow-up phase after multiple touchpoints","It eliminates the need to negotiate prices"],"answer":1}}', 42)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

INSERT INTO public.lessons (id, title, category, xp_reward, content, order_index) VALUES
('unit-43', 'Long-Term Wealth Building', 'module-8', 50, '{"slides":[{"title":"Transitioning to Buy & Hold","text":"Wholesaling generates active income—it is a job. To build true passive wealth, use your wholesaling profits to purchase and hold rental properties (buy-and-hold) or execute fix-and-flips for larger capital gains."},{"title":"Building a Portfolio","text":"Sourcing off-market deals gives you a massive advantage. Instead of wholesaling every deal, buy the best properties yourself at a discount. Build a portfolio that generates monthly rental cash flow and equity appreciation."},{"title":"Financial Freedom Roadmap","text":"Use wholesaling to fund your real estate education, build relationships with cash buyers, master contract negotiations, and scale your operations. Wholesaling is the gateway to long-term financial freedom."}],"quiz":{"question":"What is the ultimate goal of transitioning from wholesaling to buying and holding real estate?","options":["To generate more active, daily cold calling tasks","To build passive income, tax benefits, and long-term equity appreciation","To get a licensed broker position at a traditional agency"],"answer":1}}', 43)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, xp_reward = EXCLUDED.xp_reward, content = EXCLUDED.content, order_index = EXCLUDED.order_index;

